# Generated by Django 4.1.5 on 2023-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.BigIntegerField(max_length=4)),
                ('type', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('engine_size', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('features', models.CharField(max_length=255)),
            ],
        ),
    ]
